from dataclasses import dataclass
from typing import Collection, Generic, Protocol, Sequence, TypeVar

from ...app.queries.query import Query
from ...app.queries.page import Page

import uuid

T = TypeVar('T')

@dataclass
class ListRepository(Generic[T]):
    items: list[T]
    total: int

class Repository(Protocol[T]):
    def create(self, entity: T) -> str: ...
    def create_many(self, entities: Sequence[T]) -> Sequence[T]: ...

    def get(self, id: uuid.UUID) -> T | None: ...
    def get_many_by_ids(self, ids: Collection[str]) -> list[T]: ...

    def get_all(self, query: Query | None = None) -> Page[T]: ...

    def update(self, entity: T) -> T: ...

    def delete(self, id: str) -> None: ...
    def delete_many_by_ids(self, ids: Collection[str]) -> None: ...

    def exists(self, query: Query) -> bool: ...
    def delete_by(self, query: Query) -> int: ...