"""add audits

Revision ID: 65f26d6d8f3f
Revises: 87a5e34485e8
Create Date: 2026-10-10 13:13:06.646929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65f26d6d8f3f'
down_revision: Union[str, Sequence[str], None] = '87a5e34485e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=30), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'VIEW', 'LOGIN', 'LOGOUT', 'PERMISSION_CHANGE', name='auditaction'), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('is_fail', sa.Boolean(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id'),
    sa.UniqueConstraint('entity_type')
    )
    op.create_index(op.f('ix_audits_action'), 'audits', ['action'], unique=False)
    op.create_index(op.f('ix_audits_actor_id'), 'audits', ['actor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audits_actor_id'), table_name='audits')
    op.drop_index(op.f('ix_audits_action'), table_name='audits')
    op.drop_table('audits')
    # ### end Alembic commands ###
